// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql/driver"
	"fmt"
)

type State string

const (
	StateRECEIVED   State = "RECEIVED"
	StatePROCESSING State = "PROCESSING"
	StateDONE       State = "DONE"
)

func (e *State) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = State(s)
	case string:
		*e = State(s)
	default:
		return fmt.Errorf("unsupported scan type for State: %T", src)
	}
	return nil
}

type NullState struct {
	State State
	Valid bool // Valid is true if State is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullState) Scan(value interface{}) error {
	if value == nil {
		ns.State, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.State.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.State), nil
}

type Task struct {
	ID             int32
	Type           uint32
	Value          uint32
	State          State
	CreationTime   float64
	LastUpdateTime float64
}
