// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
	"fmt"
)

type State string

const (
	StateRECEIVED   State = "RECEIVED"
	StatePROCESSING State = "PROCESSING"
	StateDONE       State = "DONE"
)

func (e *State) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = State(s)
	case string:
		*e = State(s)
	default:
		return fmt.Errorf("unsupported scan type for State: %T", src)
	}
	return nil
}

type Task struct {
	ID             int32
	Type           sql.NullInt32
	Value          sql.NullInt32
	State          State
	CreationTime   float64
	LastUpdateTime float64
}
