global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: yqapp_demo-consumer
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:4040']

  - job_name: yqapp_demo-producer
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ 'host.docker.internal:4041' ]

  - job_name: 'postgres-exporter'
    honor_timestamps: true
    static_configs:
      - targets: [ 'host.docker.internal:9187' ]