metrics:
  enabled: true
  host: localhost
  port: 4317
  endpoint: "/metrics"
  environment: production

logger:
  enabled: true
  level: debug
  environment: production
  encoding: console

database:
  host: localhost
  port: 5432
  engine: postgres
  username: postgres
  password: postgres
  database: postgres

consumerService:
  messageConsumptionRate: 100

producerService:
  messageProductionRate: 1000
  maxBacklog: 99

server:
  name: yqapp-demo-server
  environment: production
  host: 0.0.0.0
  port: 3030

client:
  name: yqapp-demo-server
  environment: production
