metrics:
  enabled: true
  endpoint: "/metrics"
  environment: production

logger:
  enabled: true
  environment: production

database:
  host: localhost
  port: 5432
  engine: postgres
  username: postgres
  password: postgres
  database: postgres

consumerService:
  messageConsumptionRate: 1
  logLevel: debug
  logEncoding: json
  metricsPort: 4317

producerService:
  messageProductionRate: 10
  maxBacklog: 100
  logLevel: info
  logEncoding: console
  metricsPort: 4000

server:
  name: yqapp-demo-server
  environment: production
  host: 0.0.0.0
  port: 50051

client:
  name: yqapp-demo-client
  environment: production
